require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/item_accountings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ItemAccounting. As you add validations to ItemAccounting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ItemAccounting.create! valid_attributes
      get item_accountings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      item_accounting = ItemAccounting.create! valid_attributes
      get item_accounting_url(item_accounting)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_item_accounting_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      item_accounting = ItemAccounting.create! valid_attributes
      get edit_item_accounting_url(item_accounting)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ItemAccounting" do
        expect {
          post item_accountings_url, params: { item_accounting: valid_attributes }
        }.to change(ItemAccounting, :count).by(1)
      end

      it "redirects to the created item_accounting" do
        post item_accountings_url, params: { item_accounting: valid_attributes }
        expect(response).to redirect_to(item_accounting_url(ItemAccounting.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ItemAccounting" do
        expect {
          post item_accountings_url, params: { item_accounting: invalid_attributes }
        }.to change(ItemAccounting, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post item_accountings_url, params: { item_accounting: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested item_accounting" do
        item_accounting = ItemAccounting.create! valid_attributes
        patch item_accounting_url(item_accounting), params: { item_accounting: new_attributes }
        item_accounting.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the item_accounting" do
        item_accounting = ItemAccounting.create! valid_attributes
        patch item_accounting_url(item_accounting), params: { item_accounting: new_attributes }
        item_accounting.reload
        expect(response).to redirect_to(item_accounting_url(item_accounting))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        item_accounting = ItemAccounting.create! valid_attributes
        patch item_accounting_url(item_accounting), params: { item_accounting: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested item_accounting" do
      item_accounting = ItemAccounting.create! valid_attributes
      expect {
        delete item_accounting_url(item_accounting)
      }.to change(ItemAccounting, :count).by(-1)
    end

    it "redirects to the item_accountings list" do
      item_accounting = ItemAccounting.create! valid_attributes
      delete item_accounting_url(item_accounting)
      expect(response).to redirect_to(item_accountings_url)
    end
  end
end
