
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: bonsai_erp_development
  username: <%= ENV['USER'] %>
  password: postgres  # Uncomment and set if your PostgreSQL requires a password

test:
  <<: *default
  database: bonsai_erp_test

production:
  <<: *default
  database: bonsai_erp_production
  username: <%= ENV['BONSAI_DATABASE_USERNAME'] %>
  password: <%= ENV['BONSAI_DATABASE_PASSWORD'] %>
  host: <%= ENV['BONSAI_DATABASE_HOST'] %>
